name: CI Angular app through Github Actions
  on: [push]
  jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
          uses: actions/setup-node@v1
          with:
          node-version: 14.x
      - name: npm install, lint, test, build and deploy
          run: |
          npm ci
          npm test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
          npm run e2e -- --protractor-config=e2e/protractor-ci.conf.js --webdriver-update=false